### ISSUE TITLE
Create an optional flag for customization

### ISSUE THREAD

**Issue by jayrenn** [MicrosoftEdge/hwa-cli#4]
The default flow for the `hwa convert` command should be as seamless as possible. For those that want to have more control over the manifest configurations, we should add an optional flag for customization.

**Desired usage:** `hwa convert --more` (or `hwa convert -m` for short)

**Customization options:**
* *Device capabilities:* Location, Microphone, Webcam, Other (prompts for a string from the [list of accepted values](https://msdn.microsoft.com/en-us/library/windows/apps/Mt270968.aspx#device_capabilities))
* *Authentication and common sites:* Facebook, Google, Live, YouTube, Other
* Sites not within the scope of the start page domain

The above flow is not final, and we should iterate offline.

@jdalton recommends using [yargs](https://github.com/bcoe/yargs) for parsing the command-line arguments and [Inquirer](https://github.com/sboudrias/Inquirer.js) for the prompts.

**Comment by zackhall** [comment]
The previous commit added the optional flag. Additional work is needed to enable enhancement scenarios as described above.
